services:
  app:
    image: part12-todo-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: part12-todo-front-dev
    command: sh -c "npm install && npm run dev -- --host" # Replace the default command with added npm install and --host for Vite