# 12.17 new docker-compose.dev.yaml for development with Vite in container
services:
  app:
    image: part12-todo-front-dev
    volumes:
      - ./todo-frontend/:/usr/src/app
    #ports:
    #  - 5173:5173
    container_name: part12-todo-front-dev
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api # Use reverse proxy for API calls
    command: sh -c "npm install && npm run dev -- --host" # Replace the default command with added npm install and --host for Vite
    depends_on:
      - todo-backend # wait for the backend container to be started
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
  todo-backend:
    image: part12-todo-backend-dev # Declares which image to use
    build: 
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    #ports: 
    #  - 3000:3000
    volumes:
      - ./todo-backend/:/usr/src/app
    container_name: part12-todo-backend-dev 
    command: sh -c "npm install && npm run dev -- --host"
    environment :
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
  mongo:
    image: mongo
    #ports:
    #  - 3456:27017
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    #ports:
    #  - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data